name: dukkantek
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  top_snackbar_flutter: 1.0.1
  flutter_svg: 0.22.0
  connectivity_plus: 1.1.0
  shared_preferences: 2.0.11
  http: 0.13.4
  auto_size_text: 3.0.0
  firebase_core: 1.14.0
  firebase_auth: 3.3.12
  google_sign_in: 5.2.4
  flutter_signin_button: 2.0.0

  flutter: 
    sdk: flutter
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/

